v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
T {tt_analog_inverter -- kpex/2.5D extracted parasitics} -260 -260 0 0 0.4 0.4 {}
T {generated by layout/build_pex_schematic.py from out/tt_analog_inverter_pex.spice -- do not hand-edit} -260 -230 0 0 0.25 0.25 {}
T {visualization only: sim-post (out/inverter_tb_pex.sim.spice) is what actually re-simulates this.} -260 -200 0 0 0.25 0.25 {}
T {ntap1 tap, 0.6084Ω} -390 390 0 0 0.25 0.25 {}
T {ptap1 tap, 0.6084Ω} 210 390 0 0 0.25 0.25 {}
T {$I8 (kpex's internal PMOS-source node) is shown as int_I8; it has no other} -90 400 0 0 0.22 0.22 {}
T {connection in this diagram -- inverter.sym hides the internal device nodes.} -90 425 0 0 0.22 0.22 {}
N -90 0 -30 0 {lab=A}
N 50 0 110 0 {lab=Y}
N 0 -80 0 -30 {lab=VPWR}
N 0 30 0 80 {lab=VGND}
N -300 190 -300 250 {lab=VPWR}
N -300 310 -300 370 {lab=int_I8}
N 300 190 300 250 {lab=VGND}
N 300 310 300 370 {lab=VGND}
N -640 530 -640 590 {lab=A}
N -640 650 -640 710 {lab=VGND}
N -320 530 -320 590 {lab=A}
N -320 650 -320 710 {lab=VPWR}
N 0 530 0 590 {lab=A}
N 0 650 0 710 {lab=VSUBS}
N 320 530 320 590 {lab=A}
N 320 650 320 710 {lab=Y}
N 640 530 640 590 {lab=VGND}
N 640 650 640 710 {lab=VPWR}
N -640 830 -640 890 {lab=VGND}
N -640 950 -640 1010 {lab=VSUBS}
N -320 830 -320 890 {lab=VGND}
N -320 950 -320 1010 {lab=Y}
N 0 830 0 890 {lab=VPWR}
N 0 950 0 1010 {lab=VSUBS}
N 320 830 320 890 {lab=VPWR}
N 320 950 320 1010 {lab=Y}
N 640 830 640 890 {lab=VSUBS}
N 640 950 640 1010 {lab=Y}
C {/work/analog/xschem/inverter.sym} 0 0 0 0 {name=x1}
C {devices/lab_pin.sym} -90 0 0 1 {name=lin lab=A}
C {devices/lab_pin.sym} 110 0 0 0 {name=lout lab=Y}
C {devices/lab_pin.sym} 0 -80 0 0 {name=lvd lab=VPWR}
C {devices/lab_pin.sym} 0 80 0 2 {name=lvg lab=VGND}
C {devices/res.sym} -300 280 0 0 {name=R1 value=0.6084 m=1}
C {devices/lab_pin.sym} -300 190 0 0 {name=rtap_lo0 lab=VPWR}
C {devices/lab_pin.sym} -300 370 0 2 {name=rtap_hi0 lab=int_I8}
C {devices/res.sym} 300 280 0 0 {name=R2 value=0.6084 m=1}
C {devices/lab_pin.sym} 300 190 0 0 {name=rtap_lo1 lab=VGND}
C {devices/lab_pin.sym} 300 370 0 2 {name=rtap_hi1 lab=VGND}
C {devices/capa.sym} -640 620 0 0 {name=C1 value=363.196a m=1}
C {devices/lab_pin.sym} -640 530 0 0 {name=clo0 lab=A}
C {devices/lab_pin.sym} -640 710 0 2 {name=chi0 lab=VGND}
C {devices/capa.sym} -320 620 0 0 {name=C2 value=225.562a m=1}
C {devices/lab_pin.sym} -320 530 0 0 {name=clo1 lab=A}
C {devices/lab_pin.sym} -320 710 0 2 {name=chi1 lab=VPWR}
C {devices/capa.sym} 0 620 0 0 {name=C3 value=1.81161f m=1}
C {devices/lab_pin.sym} 0 530 0 0 {name=clo2 lab=A}
C {devices/lab_pin.sym} 0 710 0 2 {name=chi2 lab=VSUBS}
C {devices/capa.sym} 320 620 0 0 {name=C4 value=164.42a m=1}
C {devices/lab_pin.sym} 320 530 0 0 {name=clo3 lab=A}
C {devices/lab_pin.sym} 320 710 0 2 {name=chi3 lab=Y}
C {devices/capa.sym} 640 620 0 0 {name=C5 value=474.219a m=1}
C {devices/lab_pin.sym} 640 530 0 0 {name=clo4 lab=VGND}
C {devices/lab_pin.sym} 640 710 0 2 {name=chi4 lab=VPWR}
C {devices/capa.sym} -640 920 0 0 {name=C6 value=10.279f m=1}
C {devices/lab_pin.sym} -640 830 0 0 {name=clo5 lab=VGND}
C {devices/lab_pin.sym} -640 1010 0 2 {name=chi5 lab=VSUBS}
C {devices/capa.sym} -320 920 0 0 {name=C7 value=353.763a m=1}
C {devices/lab_pin.sym} -320 830 0 0 {name=clo6 lab=VGND}
C {devices/lab_pin.sym} -320 1010 0 2 {name=chi6 lab=Y}
C {devices/capa.sym} 0 920 0 0 {name=C8 value=2.25022f m=1}
C {devices/lab_pin.sym} 0 830 0 0 {name=clo7 lab=VPWR}
C {devices/lab_pin.sym} 0 1010 0 2 {name=chi7 lab=VSUBS}
C {devices/capa.sym} 320 920 0 0 {name=C9 value=376.475a m=1}
C {devices/lab_pin.sym} 320 830 0 0 {name=clo8 lab=VPWR}
C {devices/lab_pin.sym} 320 1010 0 2 {name=chi8 lab=Y}
C {devices/capa.sym} 640 920 0 0 {name=C10 value=1.47133f m=1}
C {devices/lab_pin.sym} 640 830 0 0 {name=clo9 lab=VSUBS}
C {devices/lab_pin.sym} 640 1010 0 2 {name=chi9 lab=Y}
