"""Assemble the whole-tile LVS reference netlist.

    ./run.sh python3 checks/build_tile_netlist.py     (or: make netlist)

Writes out/<TOP>_tile.spice, describing the tile the way the merged GDS is
actually built: the hand-drawn analog inverter and the LibreLane-hardened
digital macro, side by side on a shared supply.

Three sources have to be reconciled, and none of them is usable as-is:

  the PDK standard cells    transistor-level, but written with X-prefix
                            subcircuit calls
  the LibreLane macro       correct structure, but every standard cell is an
                            empty black-box subcircuit
  the xschem inverter       already in the right form; only the tile wrapper
                            around it needs replacing

KLayout LVS compares extracted *devices*, and it reads an X-prefix line as a
subcircuit instance, not a transistor -- the same trap the analog flow hits
with xschem's default netlist format. So the PDK cells are rewritten to
M-prefix device lines, the macro's black-box definitions are dropped so those
real cells are picked up instead, and a new top level wires the two halves to
the tile interface.
"""

import os
import re
import sys

PDK = "/foss/pdks/ihp-sg13g2"
STDCELLS = f"{PDK}/libs.ref/sg13g2_stdcell/spice/sg13g2_stdcell.spice"

HERE = os.path.dirname(os.path.realpath(__file__))
ANALOG = os.path.dirname(HERE)

TOP = "tt_um_mgpauly1458_inverter"
MACRO = "ms_hello"

ANALOG_NETLIST = f"{ANALOG}/out/{TOP}.spice"
MACRO_NETLIST = f"{ANALOG}/../digital/out/{MACRO}.spice"
OUT = f"{ANALOG}/out/{TOP}_tile.spice"

# Ports of the tile as LVS sees it. The unused outputs are not listed: they are
# not separate nets, they are metal sitting on VGND, which is exactly what the
# layout does and what the analog spec asks for.
TOP_PORTS = ["ua[0]", "ua[1]", "VDPWR", "VGND",
             "clk", "rst_n", "ui_in[0]", "uo_out[0]", "uo_out[1]"]

DEVICE_LINE = re.compile(r"^X(\S+)(\s+.*\ssg13_lv_[np]mos\s.*)$", re.I)


def read(path):
    if not os.path.exists(path):
        sys.exit(f"missing {path} -- run the flow that produces it first")
    return open(path).read()


def stdcells_as_devices(text):
    """Rewrite XN0/XP0 subcircuit calls into MN0/MP0 device lines."""
    out, rewritten = [], 0
    for line in text.splitlines():
        m = DEVICE_LINE.match(line)
        if m:
            line = "M" + m.group(1) + m.group(2)
            rewritten += 1
        out.append(line)
    if not rewritten:
        sys.exit(f"{STDCELLS}: no sg13_lv_* device lines found to rewrite")
    return "\n".join(out), rewritten


def strip_blackboxes(text, keep):
    """Drop every .subckt whose body is empty, except `keep`."""
    out, block, name = [], None, None
    for line in text.splitlines():
        head = re.match(r"\s*\.subckt\s+(\S+)", line, re.I)
        if head:
            block, name = [line], head.group(1)
            continue
        if block is not None:
            block.append(line)
            if re.match(r"\s*\.ends\b", line, re.I):
                body = [b for b in block[1:-1]
                        if b.strip() and not b.strip().startswith("*")]
                if body or name == keep:
                    out.extend(block)
                block = None
            continue
        out.append(line)
    if block is not None:
        sys.exit(f"unterminated .subckt {name}")
    return "\n".join(out)


def subckt(text, name):
    """Extract one .subckt ... .ends block verbatim."""
    m = re.search(rf"^\s*\.subckt\s+{re.escape(name)}\b.*?^\s*\.ends\b.*?$",
                  text, re.I | re.M | re.S)
    if not m:
        sys.exit(f"no .subckt {name} found")
    return m.group(0)


def main():
    cells, n = stdcells_as_devices(read(STDCELLS))
    macro = strip_blackboxes(read(MACRO_NETLIST), keep=MACRO)
    inverter = subckt(read(ANALOG_NETLIST), "inverter")

    top = "\n".join([
        f".subckt {TOP} " + " ".join(TOP_PORTS),
        "* the analog half: gate on ua[1], drain on ua[0]",
        "x1 ua[1] ua[0] VDPWR VGND inverter",
        "* the digital half, as hardened by LibreLane",
        f"xdig VGND VDPWR ui_in[0] clk rst_n uo_out[0] uo_out[1] {MACRO}",
        ".ends",
    ])

    with open(OUT, "w") as fh:
        fh.write("\n\n".join([
            f"* Whole-tile LVS netlist for {TOP}, generated by "
            f"checks/{os.path.basename(__file__)} -- do not edit.",
            f"* ---- standard cells ({n} device lines rewritten X -> M) ----",
            cells,
            f"* ---- digital macro, black-box definitions removed ----",
            macro,
            "* ---- analog inverter, from the xschem schematic ----",
            inverter,
            "* ---- the tile ----",
            top,
            "",
        ]))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
