#!/usr/bin/env python3
"""Rewrite kpex's extracted netlist so ngspice can run it in the pre-layout netlist's place.

    python3 layout/build_sim_post.py [--pex out/pex/tt_analog_ring_pex.spice] [--out out/pex/tt_analog_ring.pex.spice]

Writes a `.subckt tt_analog_ring` with the pre-layout ports (code[7:0] enable clk_out VPWR VGND); kpex's capacitors are kept as written.
- kpex's `M` lines become `X` calls with w/l/ng: the PDK's sg13_lv_nmos/pmos ngspice models are subcircuits, so an `M` line will not run.
- `$name` nets become `n_name` (`$` starts a comment in ngspice); VSUBS becomes VGND (substrate tied to ground through guard ring and ties).
- Labelled internal nets (vbp, vbn, s0..s10, b1) keep their names and stay probeable as xdut.<name>.
"""
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PORTS = [f"code[{k}]" for k in range(8)] + ["enable", "clk_out", "VPWR", "VGND"]


def netname(n):
    n = n.replace("\\", "")
    if n == "VSUBS":
        return "VGND"
    if n.startswith("$"):
        return "n_" + n[1:]
    return n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pex", default=os.path.join(ROOT, "out", "pex", "tt_analog_ring_pex.spice"))
    ap.add_argument("--out", default=os.path.join(ROOT, "out", "pex", "tt_analog_ring.pex.spice"))
    a = ap.parse_args()

    # join continuation lines
    lines = []
    for raw in open(a.pex):
        raw = raw.rstrip("\n")
        if raw.startswith("+") and lines:
            lines[-1] += " " + raw[1:].strip()
        else:
            lines.append(raw)

    out = ["* tt_analog_ring, post-layout: devices + kpex 2.5D parasitic capacitances",
           f"* GENERATED by analog/layout/build_sim_post.py from {os.path.relpath(a.pex, ROOT)} - do not edit.",
           "* Same ports as spice/tt_analog_ring.spice; internal nets vbp, vbn, s0..s10, b1 keep their names.",
           f".subckt tt_analog_ring {' '.join(PORTS)}"]
    ndev = ncap = 0
    for line in lines:
        s = line.strip()
        if not s or s.startswith("*") or s.upper().startswith(".SUBCKT") or s.upper().startswith(".ENDS"):
            continue
        tok = s.split()
        if tok[0].startswith("M"):
            d, g, sx, b, model = (netname(t) for t in tok[1:6])
            params = dict(p.split("=", 1) for p in tok[6:] if "=" in p)
            w, l = params.get("W", params.get("w")), params.get("L", params.get("l"))
            name = "XM" + re.sub(r"[^A-Za-z0-9_]", "", tok[0][1:])
            out.append(f"{name} {d} {g} {sx} {b} {model} w={w.lower()} l={l.lower()} ng=1")
            ndev += 1
        elif tok[0].startswith("C"):
            out.append(f"{tok[0].replace('$', '')} {netname(tok[1])} {netname(tok[2])} {tok[3]}")
            ncap += 1
        else:
            raise SystemExit(f"unexpected line in kpex output: {line}")
    out.append(".ends tt_analog_ring")
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"{a.out}: {ndev} devices, {ncap} parasitic capacitors")


if __name__ == "__main__":
    main()
