#!/usr/bin/env python3
"""Turn kpex's extracted netlist into one ngspice can simulate in the macro's place.

    python3 layout/build_sim_post.py [--pex out/pex/tt_analog_ring_pex.spice]
                                     [--out out/pex/tt_analog_ring.pex.spice]

kpex (2.5D) writes a `.SUBCKT tt_analog_ring` whose ports are every labelled
net (the pins plus vbp, vbn, b1, s0..s10), whose transistors are SPICE `M`
device lines naming `sg13_lv_nmos`/`sg13_lv_pmos` (which in this PDK's
ngspice library are *subcircuits*, so an `M` line will not run), whose
unlabelled nets are called `$122`, and which has a `VSUBS` substrate node.
This rewrites it so that:

  * the subcircuit has the macro's real ports, in the pre-layout order
    (code[7:0] enable clk_out VPWR VGND), so any deck that includes
    spice/tt_analog_ring.spice can include this file instead;
  * every `M` becomes an `X` call with w/l/ng, like the pre-layout netlist;
  * `$`-names become `n_...` (a `$` starts a comment in ngspice);
  * VSUBS is VGND (the substrate is tied to ground through the guard ring
    and the tie columns; the caps to it are caps to ground);
  * the labelled internal nets keep their names, so vbp, vbn, s0..s10, b1
    stay probeable as xdut.<name>.

The parasitic capacitors are kept as written (kpex's values, in aF/fF).
"""
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PORTS = [f"code[{k}]" for k in range(8)] + ["enable", "clk_out", "VPWR", "VGND"]


def netname(n):
    n = n.replace("\\", "")
    if n == "VSUBS":
        return "VGND"
    if n.startswith("$"):
        return "n_" + n[1:]
    return n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pex", default=os.path.join(ROOT, "out", "pex", "tt_analog_ring_pex.spice"))
    ap.add_argument("--out", default=os.path.join(ROOT, "out", "pex", "tt_analog_ring.pex.spice"))
    a = ap.parse_args()

    # join continuation lines
    lines = []
    for raw in open(a.pex):
        raw = raw.rstrip("\n")
        if raw.startswith("+") and lines:
            lines[-1] += " " + raw[1:].strip()
        else:
            lines.append(raw)

    out = ["* tt_analog_ring, post-layout: devices + kpex 2.5D parasitic capacitances",
           f"* GENERATED by analog/layout/build_sim_post.py from {os.path.relpath(a.pex, ROOT)} - do not edit.",
           "* Same ports as spice/tt_analog_ring.spice; internal nets vbp, vbn, s0..s10, b1 keep their names.",
           f".subckt tt_analog_ring {' '.join(PORTS)}"]
    ndev = ncap = 0
    for line in lines:
        s = line.strip()
        if not s or s.startswith("*") or s.upper().startswith(".SUBCKT") or s.upper().startswith(".ENDS"):
            continue
        tok = s.split()
        if tok[0].startswith("M"):
            d, g, sx, b, model = (netname(t) for t in tok[1:6])
            params = dict(p.split("=", 1) for p in tok[6:] if "=" in p)
            w, l = params.get("W", params.get("w")), params.get("L", params.get("l"))
            name = "XM" + re.sub(r"[^A-Za-z0-9_]", "", tok[0][1:])
            out.append(f"{name} {d} {g} {sx} {b} {model} w={w.lower()} l={l.lower()} ng=1")
            ndev += 1
        elif tok[0].startswith("C"):
            out.append(f"{tok[0].replace('$', '')} {netname(tok[1])} {netname(tok[2])} {tok[3]}")
            ncap += 1
        else:
            raise SystemExit(f"unexpected line in kpex output: {line}")
    out.append(".ends tt_analog_ring")
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"{a.out}: {ndev} devices, {ncap} parasitic capacitors")


if __name__ == "__main__":
    main()
