"""Render the kpex-extracted parasitic netlist as an xschem schematic, purely
for looking at -- a picture of what PEX found, laid over the same inverter
block used everywhere else in this directory.

    ./run.sh python3 layout/build_pex_schematic.py

Reads analog/out/tt_analog_inverter_pex.spice (make pex) and writes
analog/xschem/tt_analog_inverter_pex_viz.sch.

Named _viz, not _pex, deliberately: xschem netlists a schematic to
out/<basename>.spice, and out/tt_analog_inverter_pex.spice is kpex's own
artifact -- giving this schematic the same base name would let `make xschem`
or a stray netlist run silently overwrite kpex's output with this
schematic's (trivial, wrapper-only) one instead.

This is NOT the netlist used to simulate post-layout -- that is
out/inverter_tb_pex.sim.spice, built by build_sim_post.py and driven straight
by ngspice, no xschem involved. This script exists only to make the extracted
R/C network visible: the two tap resistors (drawn as extracted, including the
VGND->VGND self-loop kpex reports for the guard-ring tap) and all ten
pairwise coupling capacitors among {A, Y, VPWR, VGND, VSUBS}, wired the same
way every other schematic here wires a net -- by a matching `lab=` on a wire
or pin, not by physical touching.
"""

import os
import re

IN = os.path.join(os.path.dirname(__file__), "..", "out", "tt_analog_inverter_pex.spice")
OUT = os.path.join(os.path.dirname(__file__), "..", "xschem", "tt_analog_inverter_pex_viz.sch")

pex = open(IN).read()

caps = []  # (net1, net2, value)
for m in re.finditer(r"^Cext_\d+\s+(\S+)\s+(\S+)\s+(\S+)$", pex, re.MULTILINE):
    caps.append((m.group(1), m.group(2), m.group(3)))

resistors = []  # (net1, net2, value, tapname)
for m in re.finditer(r"^R\S+\s+(\S+)\s+(\S+)\s+([\d.eE+-]+)\s+(\S+)\s+P=", pex, re.MULTILINE):
    net1, net2, value, tap = m.groups()
    net2 = net2.replace("\\$", "$").replace("$", "int_")  # $I8 -> int_I8: keep '$' out of labels
    resistors.append((net1, net2, value, tap))

if not caps or not resistors:
    raise SystemExit(f"parsed nothing out of {IN} -- has `make pex` been run?")

lines = []
lines.append("v {xschem version=3.4.8RC file_version=1.3}")
lines.append("G {}")
lines.append("K {}")
lines.append("V {}")
lines.append("S {}")
lines.append("E {}")

wires = []
comps = []


def lab_pin(x, y, rot, flip, name, lab):
    comps.append(f"C {{devices/lab_pin.sym}} {x} {y} {rot} {flip} {{name={name} lab={lab}}}")


def wire(x1, y1, x2, y2, lab=None):
    tag = f" {{lab={lab}}}" if lab else " {}"
    wires.append(f"N {x1} {y1} {x2} {y2}{tag}")


def text(x, y, s, size=0.35):
    comps.append(f'T {{{s}}} {x} {y} 0 0 {size} {size} {{}}')


# ---------------------------------------------------------------- the core
# Exactly the wrapper tt_analog_inverter.sch uses: inverter.sym with its A/Y
# pins west/east and VPWR/VGND north/south, established here as named nets
# that everything below hooks onto purely by matching `lab=`.
comps.append("C {inverter.sym} 0 0 0 0 {name=x1}")
wire(-30, 0, -90, 0, "A")
wire(50, 0, 110, 0, "Y")
wire(0, -30, 0, -80, "VPWR")
wire(0, 30, 0, 80, "VGND")
lab_pin(-90, 0, 0, 1, "lin", "A")
lab_pin(110, 0, 0, 0, "lout", "Y")
lab_pin(0, -80, 0, 0, "lvd", "VPWR")
lab_pin(0, 80, 0, 2, "lvg", "VGND")
text(-260, -260, "tt_analog_inverter -- kpex/2.5D extracted parasitics", 0.4)
text(-260, -230, "generated by layout/build_pex_schematic.py from out/tt_analog_inverter_pex.spice -- do not hand-edit", 0.25)
text(-260, -200, "visualization only: sim-post (out/inverter_tb_pex.sim.spice) is what actually re-simulates this.", 0.25)

# ------------------------------------------------------------ tap resistors
# Drawn exactly as kpex reported them, self-loop included: R$4 really is
# VGND -> VGND in the extracted netlist (the guard ring's own tap resistance,
# with no other node in the flattened view to distinguish its far end).
for i, (n1, n2, value, tap) in enumerate(resistors):
    x = -300 if i == 0 else 300
    y = 280
    comps.append(f"C {{devices/res.sym}} {x} {y} 0 0 {{name=R{i+1} value={value} m=1}}")
    wire(x, y - 30, x, y - 90, n1)
    wire(x, y + 30, x, y + 90, n2)
    lab_pin(x, y - 90, 0, 0, f"rtap_lo{i}", n1)
    lab_pin(x, y + 90, 0, 2, f"rtap_hi{i}", n2)
    text(x - 90, y + 110, f"{tap} tap, {value}Ω", 0.25)

text(-90, 400, "$I8 (kpex's internal PMOS-source node) is shown as int_I8; it has no other", 0.22)
text(-90, 425, "connection in this diagram -- inverter.sym hides the internal device nodes.", 0.22)

# ------------------------------------------------------ coupling capacitors
# All 10 pairs among {A, Y, VPWR, VGND, VSUBS}, 5 per row, laid out in the
# order kpex printed them. Each is wired purely by `lab=`, same idiom as the
# rest of this directory's schematics -- no rail geometry to keep consistent.
COLS = 5
COL_DX = 320
ROW_DY = 300
X0 = -(COLS - 1) * COL_DX // 2
Y0 = 620

for i, (n1, n2, value) in enumerate(caps):
    col, row = i % COLS, i // COLS
    x = X0 + col * COL_DX
    y = Y0 + row * ROW_DY
    comps.append(f"C {{devices/capa.sym}} {x} {y} 0 0 {{name=C{i+1} value={value} m=1}}")
    wire(x, y - 30, x, y - 90, n1)
    wire(x, y + 30, x, y + 90, n2)
    lab_pin(x, y - 90, 0, 0, f"clo{i}", n1)
    lab_pin(x, y + 90, 0, 2, f"chi{i}", n2)

lines += wires
lines += comps

with open(OUT, "w") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"wrote {OUT}  ({len(caps)} caps, {len(resistors)} tap resistors)")
