#!/usr/bin/env python3
"""Assemble the verification results into docs/analog_verification_results.md.

    python3 verify/report.py

Each test script leaves its tables in out/verify/<name>.md; this concatenates
them in reading order with a header saying what produced them. The strategy
and the reading of the numbers are in docs/analog_verification.md, written by
hand; this file is the generated appendix it refers to.
"""
import datetime
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "out", "verify")
DOCS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs")
ORDER = ["dac", "bias", "stage", "nand", "buffer", "ring", "pex", "ring_post", "env", "env_post"]

parts = ["# Analog block verification: results\n",
         "GENERATED by `make -C analog verify sim-post verify-ring-post verify-env verify-env-post` (analog/verify/*.py, ngspice in the iic-osic-tools container) on "
         f"{datetime.date.today().isoformat()}. The strategy, and what the numbers mean, is in "
         "[analog_verification.md](analog_verification.md). Do not edit; rerun.\n",
         "Corner names: process (tt, ss, ff, sf, fs) _ temperature _ supply. `SIGNOFF` corners are the three the "
         "tile's STA uses: tt 27 C 1.20 V, ss 125 C 1.08 V, ff -40 C 1.32 V.\n"]
for name in ORDER:
    p = os.path.join(OUT, name + ".md")
    if os.path.exists(p):
        parts.append("\n---\n\n" + open(p).read())
    else:
        parts.append(f"\n---\n\n## {name}: not run\n")
path = os.path.join(DOCS, "analog_verification_results.md")
with open(path, "w") as fh:
    fh.write("\n".join(parts))
print("wrote", path)
